### ISSUE TITLE
Marker Icons

### ISSUE THREAD

**Issue by ajdavidson** [ajdavidson/bus-tracker#1]
Update marker icons to svg using the maps api svg path integration

**Comment by ajdavidson** [comment]
ref this code 
https://github.com/googlemaps/js-samples/blob/859e6b728b01bdec595224c5a767470f2f8b805e/dist/samples/marker-symbol-custom/index.js
https://developers.google.com/maps/documentation/javascript/markers

**Comment by ajdavidson** [comment]
found svg bus red and blue images and imported into A.I.

**Comment by ajdavidson** [comment]
I have the svg path generating the red and blue icons dynamically with stroke control.

**Comment by ajd-pro** [comment]
I tried different options for custom vector markers including Google icon library, fontAwesome etc.  But ended up exporting the pure vector path from AI from a google icon bus shape.  Maps API can incor[porate and gives other properties to maipulate like 'fill' 'stroke' etc.  Thsi solutiom is simple, library independent, and looks exactly like the original vision for this upgrade.  Done and stylin' :sunglasses:

**Comment by ajdavidson** [comment]
Perfect looking!  Ready for releease.
